// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2rDdd2IGAB5dazVDj_kMkp_enHo35aZY',
    appId: '1:185722322306:web:37ea83038cb36a9222239b',
    messagingSenderId: '185722322306',
    projectId: 'taka-taka-app',
    authDomain: 'taka-taka-app.firebaseapp.com',
    storageBucket: 'taka-taka-app.appspot.com',
    measurementId: 'G-GWF5E1HPWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQk_K8LvXFD1JlKgpe1QgsR_HSL3DUv0',
    appId: '1:185722322306:android:014f21f0a44da6b422239b',
    messagingSenderId: '185722322306',
    projectId: 'taka-taka-app',
    storageBucket: 'taka-taka-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnt4zG4ab4vG__tOlo7gA69Z2Ku5l4rSI',
    appId: '1:185722322306:ios:6d29b92305baad4422239b',
    messagingSenderId: '185722322306',
    projectId: 'taka-taka-app',
    storageBucket: 'taka-taka-app.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnt4zG4ab4vG__tOlo7gA69Z2Ku5l4rSI',
    appId: '1:185722322306:ios:6d29b92305baad4422239b',
    messagingSenderId: '185722322306',
    projectId: 'taka-taka-app',
    storageBucket: 'taka-taka-app.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2rDdd2IGAB5dazVDj_kMkp_enHo35aZY',
    appId: '1:185722322306:web:09b14721e3b73bc422239b',
    messagingSenderId: '185722322306',
    projectId: 'taka-taka-app',
    authDomain: 'taka-taka-app.firebaseapp.com',
    storageBucket: 'taka-taka-app.appspot.com',
    measurementId: 'G-6BCC5VVPPP',
  );
}
